### ISSUE TITLE
Problems with the fake-delivery-api

### ISSUE THREAD

**Issue by brnrj** [andrei-tarnauceanu/serverless-apps-with-node-and-claudiajs#1]
Hello, I'm not able to connect to the delivery api from the chapter 4 at

https://fake-delivery-api.effortlessserverless.com/delivery
https://some-like-it-hot.effortlessserverless.com/delivery

both return the error
{
    "errorMessage": "getaddrinfo ENOTFOUND fake-delivery-api.effortlessserverless.com"
}

there is another address?

**Comment by andrei-tarnauceanu** [comment]
Hi, this code is from a manning course.  
https://www.manning.com/books/serverless-applications-with-node-js
Unfortunately I can't help you with this issue.
